{% set version = '0.4.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-duckplyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/duckplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/duckplyr/duckplyr_{{ version }}.tar.gz
  sha256: 3e23255a91f9ebc8a8e0fb2fb32d96e16fa7620527d912cd8ec13fa3f32d2fd3

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi
    - r-cli
    - r-collections
    - r-dplyr >=1.1.4
    - r-duckdb >=0.10.2
    - r-glue
    - r-jsonlite
    - r-lifecycle
    - r-rlang >=1.0.6
    - r-tibble
    - r-tidyselect
    - r-vctrs >=0.6.3
  run:
    - r-base
    - r-dbi
    - r-cli
    - r-collections
    - r-dplyr >=1.1.4
    - r-duckdb >=0.10.2
    - r-glue
    - r-jsonlite
    - r-lifecycle
    - r-rlang >=1.0.6
    - r-tibble
    - r-tidyselect
    - r-vctrs >=0.6.3

test:
  commands:
    - $R -e "library('duckplyr')"           # [not win]
    - "\"%R%\" -e \"library('duckplyr')\""  # [win]

about:
  home: https://duckdblabs.github.io/duckplyr/
  dev_url: https://github.com/duckdblabs/duckplyr
  license: MIT
  summary: A drop-in replacement for 'dplyr', powered by 'DuckDB' for performance. Also defines
    a set of generics that provide a low-level implementer's interface for the high-level
    user interface of 'dplyr'.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - vitodelgrec

# Package: duckplyr
# Title: A 'DuckDB'-Backed Version of 'dplyr'
# Version: 0.4.1
# Authors@R: c( person("Hannes", "Muhleisen", role = "aut", comment = c(ORCID = "0000-0001-8552-0029")), person("Kirill", "Muller", , "kirill@cynkra.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1416-3412")), person("Posit Software, PBC", role = c("cph", "fnd")) )
# Description: A drop-in replacement for 'dplyr', powered by 'DuckDB' for performance. Also defines a set of generics that provide a low-level implementer's interface for the high-level user interface of 'dplyr'.
# License: MIT + file LICENSE
# URL: https://duckdblabs.github.io/duckplyr/, https://github.com/duckdblabs/duckplyr
# BugReports: https://github.com/duckdblabs/duckplyr/issues
# Depends: R (>= 4.1.0)
# Imports: cli, collections, DBI, dplyr (>= 1.1.4), duckdb (>= 0.10.2), glue, jsonlite, lifecycle, rlang (>= 1.0.6), tibble, tidyselect, utils, vctrs (>= 0.6.3)
# Suggests: arrow, brio, constructive (>= 1.0.0), curl, dbplyr, hms, lobstr, lubridate, palmerpenguins, pillar, prettycode, purrr, qs, reprex, rstudioapi, testthat (>= 3.1.5), usethis, withr
# Config/Needs/check: anthonynorth/roxyglobals
# Config/testthat/edition: 3
# Config/testthat/parallel: false
# Config/testthat/start-first: rel_api, tpch, as_duckplyr_df, mutate, filter, count-tally
# Encoding: UTF-8
# RoxygenNote: 7.3.2.9000
# NeedsCompilation: no
# Packaged: 2024-07-12 10:34:25 UTC; kirill
# Author: Hannes Muhleisen [aut] (<https://orcid.org/0000-0001-8552-0029>), Kirill Muller [aut, cre] (<https://orcid.org/0000-0002-1416-3412>), Posit Software, PBC [cph, fnd]
# Maintainer: Kirill Muller <kirill@cynkra.com>
# Repository: CRAN
# Date/Publication: 2024-07-12 10:50:02 UTC
